name: Gunagzheng Li
title: Jekflix | A personal blog
description: Jekflix is a template for Jekyll inspired by Netflix and made by
  Thiago Rossener. aa
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: gli34@sheffield.ac.uk 
disqus_username: disqus_username
