name: Gunagzheng Li
title: Guangzheng Li | A Personal Blog
description: This is a personal Blog for Guangzheng Li, locates on Github and based on Jekflix 
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: Personal CV
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: gli34@sheffield.ac.uk 
disqus_username: GuangzhengLi
